BEGIN;

ALTER TABLE cortes ADD COLUMN IF NOT EXISTS monto_inicial NUMERIC(12,2);
ALTER TABLE cortes ADD COLUMN IF NOT EXISTS abierto_por UUID REFERENCES usuarios(id);
ALTER TABLE cortes ADD COLUMN IF NOT EXISTS abierto_at TIMESTAMPTZ;

COMMIT;
