BEGIN;

ALTER TABLE ventas ADD COLUMN IF NOT EXISTS total NUMERIC(12,2);
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS tipo_pago VARCHAR(20);
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS cliente_id UUID REFERENCES clientes(id);
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS fecha_vencimiento DATE;
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS saldo_pendiente NUMERIC(12,2) DEFAULT 0;
ALTER TABLE ventas ADD COLUMN IF NOT EXISTS estado VARCHAR(20);

COMMIT;
